stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw


  data_preprocessing:
    cmd: python3 src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim


  model_building:
    cmd: python3 src/Model_builder.py
    deps:
      - src/Model_builder.py
      - data/interim/train_processed.csv
    params:
      - model_builder.max_features
      - model_builder.ngram_range
      - model_builder.learning_rate
      - model_builder.max_depth
      - model_builder.n_estimators
    outs:
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl


  model_evaluation:
    cmd: python3 src/model_eval.py
    deps:
      - src/model_eval.py
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl
      - data/interim/test_processed.csv
    outs:
      - experiment_info.json
      - confusion_matrix.png
  
  model_registration:
    cmd: python3 src/register_model.py
    deps:
      - src/register_model.py
      - experiment_info.json
